'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSNavy
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimbrarXMLSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class TimbrarXML
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ActivarDesactivarClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidarRFCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarPruebaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarSAPPruebasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbrarSAPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarComprobanteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarComprobantePruebasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenerarPemOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SubirArchivoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DescargarArchivoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EstatusComprobanteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbresConsumidosRFechaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TimbresConsumidosMesActualOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ComercializadoraGTFernandoSr.My.MySettings.Default.PriceMarket_WSNavy_TimbrarXML
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ActivarDesactivarClienteCompleted As ActivarDesactivarClienteCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidarRFCCompleted As ValidarRFCCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarClienteCompleted As RegistrarClienteCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarCompleted As TimbrarCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarPruebaCompleted As TimbrarPruebaCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarSAPPruebasCompleted As TimbrarSAPPruebasCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbrarSAPCompleted As TimbrarSAPCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarComprobanteCompleted As CancelarComprobanteCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarComprobantePruebasCompleted As CancelarComprobantePruebasCompletedEventHandler
        
        '''<remarks/>
        Public Event GenerarPemCompleted As GenerarPemCompletedEventHandler
        
        '''<remarks/>
        Public Event SubirArchivoCompleted As SubirArchivoCompletedEventHandler
        
        '''<remarks/>
        Public Event DescargarArchivoCompleted As DescargarArchivoCompletedEventHandler
        
        '''<remarks/>
        Public Event EstatusComprobanteCompleted As EstatusComprobanteCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbresConsumidosRFechaCompleted As TimbresConsumidosRFechaCompletedEventHandler
        
        '''<remarks/>
        Public Event TimbresConsumidosMesActualCompleted As TimbresConsumidosMesActualCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivarDesactivarCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActivarDesactivarCliente(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String, ByVal Activar As Boolean) As RespuestaActivarCliente
            Dim results() As Object = Me.Invoke("ActivarDesactivarCliente", New Object() {Usuario, PWD, RfcEmisor, Activar})
            Return CType(results(0),RespuestaActivarCliente)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ActivarDesactivarClienteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String, ByVal Activar As Boolean)
            Me.ActivarDesactivarClienteAsync(Usuario, PWD, RfcEmisor, Activar, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActivarDesactivarClienteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String, ByVal Activar As Boolean, ByVal userState As Object)
            If (Me.ActivarDesactivarClienteOperationCompleted Is Nothing) Then
                Me.ActivarDesactivarClienteOperationCompleted = AddressOf Me.OnActivarDesactivarClienteOperationCompleted
            End If
            Me.InvokeAsync("ActivarDesactivarCliente", New Object() {Usuario, PWD, RfcEmisor, Activar}, Me.ActivarDesactivarClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnActivarDesactivarClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActivarDesactivarClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActivarDesactivarClienteCompleted(Me, New ActivarDesactivarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarRFC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidarRFC(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String) As RespuestaActivarCliente
            Dim results() As Object = Me.Invoke("ValidarRFC", New Object() {Usuario, PWD, RfcEmisor})
            Return CType(results(0),RespuestaActivarCliente)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidarRFCAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String)
            Me.ValidarRFCAsync(Usuario, PWD, RfcEmisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidarRFCAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String, ByVal userState As Object)
            If (Me.ValidarRFCOperationCompleted Is Nothing) Then
                Me.ValidarRFCOperationCompleted = AddressOf Me.OnValidarRFCOperationCompleted
            End If
            Me.InvokeAsync("ValidarRFC", New Object() {Usuario, PWD, RfcEmisor}, Me.ValidarRFCOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidarRFCOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidarRFCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidarRFCCompleted(Me, New ValidarRFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarCliente(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String) As RespuestaAgregarCliente
            Dim results() As Object = Me.Invoke("RegistrarCliente", New Object() {Usuario, PWD, RfcEmisor})
            Return CType(results(0),RespuestaAgregarCliente)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarClienteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String)
            Me.RegistrarClienteAsync(Usuario, PWD, RfcEmisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarClienteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RfcEmisor As String, ByVal userState As Object)
            If (Me.RegistrarClienteOperationCompleted Is Nothing) Then
                Me.RegistrarClienteOperationCompleted = AddressOf Me.OnRegistrarClienteOperationCompleted
            End If
            Me.InvokeAsync("RegistrarCliente", New Object() {Usuario, PWD, RfcEmisor}, Me.RegistrarClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarClienteCompleted(Me, New RegistrarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Timbrar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Timbrar(ByVal Usuario As String, ByVal PWD As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As RespuestaTimbrado
            Dim results() As Object = Me.Invoke("Timbrar", New Object() {Usuario, PWD, Archivo})
            Return CType(results(0),RespuestaTimbrado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte)
            Me.TimbrarAsync(Usuario, PWD, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.TimbrarOperationCompleted Is Nothing) Then
                Me.TimbrarOperationCompleted = AddressOf Me.OnTimbrarOperationCompleted
            End If
            Me.InvokeAsync("Timbrar", New Object() {Usuario, PWD, Archivo}, Me.TimbrarOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarCompleted(Me, New TimbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbrarPrueba", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarPrueba(ByVal Usuario As String, ByVal PWD As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As RespuestaTimbrado
            Dim results() As Object = Me.Invoke("TimbrarPrueba", New Object() {Usuario, PWD, Archivo})
            Return CType(results(0),RespuestaTimbrado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarPruebaAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte)
            Me.TimbrarPruebaAsync(Usuario, PWD, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarPruebaAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.TimbrarPruebaOperationCompleted Is Nothing) Then
                Me.TimbrarPruebaOperationCompleted = AddressOf Me.OnTimbrarPruebaOperationCompleted
            End If
            Me.InvokeAsync("TimbrarPrueba", New Object() {Usuario, PWD, Archivo}, Me.TimbrarPruebaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarPruebaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarPruebaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarPruebaCompleted(Me, New TimbrarPruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbrarSAPPruebas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarSAPPruebas(ByVal Usuario As String, ByVal PWD As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As RespuestaTimbrado
            Dim results() As Object = Me.Invoke("TimbrarSAPPruebas", New Object() {Usuario, PWD, Archivo})
            Return CType(results(0),RespuestaTimbrado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarSAPPruebasAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte)
            Me.TimbrarSAPPruebasAsync(Usuario, PWD, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarSAPPruebasAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.TimbrarSAPPruebasOperationCompleted Is Nothing) Then
                Me.TimbrarSAPPruebasOperationCompleted = AddressOf Me.OnTimbrarSAPPruebasOperationCompleted
            End If
            Me.InvokeAsync("TimbrarSAPPruebas", New Object() {Usuario, PWD, Archivo}, Me.TimbrarSAPPruebasOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarSAPPruebasOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarSAPPruebasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarSAPPruebasCompleted(Me, New TimbrarSAPPruebasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbrarSAP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbrarSAP(ByVal Usuario As String, ByVal PWD As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As RespuestaTimbrado
            Dim results() As Object = Me.Invoke("TimbrarSAP", New Object() {Usuario, PWD, Archivo})
            Return CType(results(0),RespuestaTimbrado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbrarSAPAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte)
            Me.TimbrarSAPAsync(Usuario, PWD, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbrarSAPAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.TimbrarSAPOperationCompleted Is Nothing) Then
                Me.TimbrarSAPOperationCompleted = AddressOf Me.OnTimbrarSAPOperationCompleted
            End If
            Me.InvokeAsync("TimbrarSAP", New Object() {Usuario, PWD, Archivo}, Me.TimbrarSAPOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbrarSAPOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbrarSAPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbrarSAPCompleted(Me, New TimbrarSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarComprobante", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarComprobante(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String) As RespuestaCancelacion
            Dim results() As Object = Me.Invoke("CancelarComprobante", New Object() {Usuario, PWD, RFCEmisor, UUID})
            Return CType(results(0),RespuestaCancelacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarComprobanteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String)
            Me.CancelarComprobanteAsync(Usuario, PWD, RFCEmisor, UUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarComprobanteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String, ByVal userState As Object)
            If (Me.CancelarComprobanteOperationCompleted Is Nothing) Then
                Me.CancelarComprobanteOperationCompleted = AddressOf Me.OnCancelarComprobanteOperationCompleted
            End If
            Me.InvokeAsync("CancelarComprobante", New Object() {Usuario, PWD, RFCEmisor, UUID}, Me.CancelarComprobanteOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarComprobanteOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarComprobanteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarComprobanteCompleted(Me, New CancelarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarComprobantePruebas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarComprobantePruebas(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String) As RespuestaCancelacion
            Dim results() As Object = Me.Invoke("CancelarComprobantePruebas", New Object() {Usuario, PWD, RFCEmisor, UUID})
            Return CType(results(0),RespuestaCancelacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarComprobantePruebasAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String)
            Me.CancelarComprobantePruebasAsync(Usuario, PWD, RFCEmisor, UUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarComprobantePruebasAsync(ByVal Usuario As String, ByVal PWD As String, ByVal RFCEmisor As String, ByVal UUID As String, ByVal userState As Object)
            If (Me.CancelarComprobantePruebasOperationCompleted Is Nothing) Then
                Me.CancelarComprobantePruebasOperationCompleted = AddressOf Me.OnCancelarComprobantePruebasOperationCompleted
            End If
            Me.InvokeAsync("CancelarComprobantePruebas", New Object() {Usuario, PWD, RFCEmisor, UUID}, Me.CancelarComprobantePruebasOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarComprobantePruebasOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarComprobantePruebasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarComprobantePruebasCompleted(Me, New CancelarComprobantePruebasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarPem", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerarPem(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String) As String
            Dim results() As Object = Me.Invoke("GenerarPem", New Object() {Usuario, PWD, Emisor})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerarPemAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String)
            Me.GenerarPemAsync(Usuario, PWD, Emisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerarPemAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal userState As Object)
            If (Me.GenerarPemOperationCompleted Is Nothing) Then
                Me.GenerarPemOperationCompleted = AddressOf Me.OnGenerarPemOperationCompleted
            End If
            Me.InvokeAsync("GenerarPem", New Object() {Usuario, PWD, Emisor}, Me.GenerarPemOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerarPemOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerarPemCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerarPemCompleted(Me, New GenerarPemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubirArchivo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SubirArchivo(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal NombreArchivo As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As String
            Dim results() As Object = Me.Invoke("SubirArchivo", New Object() {Usuario, PWD, Emisor, NombreArchivo, Archivo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SubirArchivoAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal NombreArchivo As String, ByVal Archivo() As Byte)
            Me.SubirArchivoAsync(Usuario, PWD, Emisor, NombreArchivo, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SubirArchivoAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal NombreArchivo As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.SubirArchivoOperationCompleted Is Nothing) Then
                Me.SubirArchivoOperationCompleted = AddressOf Me.OnSubirArchivoOperationCompleted
            End If
            Me.InvokeAsync("SubirArchivo", New Object() {Usuario, PWD, Emisor, NombreArchivo, Archivo}, Me.SubirArchivoOperationCompleted, userState)
        End Sub
        
        Private Sub OnSubirArchivoOperationCompleted(ByVal arg As Object)
            If (Not (Me.SubirArchivoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SubirArchivoCompleted(Me, New SubirArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DescargarArchivo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DescargarArchivo(ByVal Usuario As String, ByVal PWD As String, ByVal NombreArchivo As String) As RespuestaDescargarArchivo
            Dim results() As Object = Me.Invoke("DescargarArchivo", New Object() {Usuario, PWD, NombreArchivo})
            Return CType(results(0),RespuestaDescargarArchivo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DescargarArchivoAsync(ByVal Usuario As String, ByVal PWD As String, ByVal NombreArchivo As String)
            Me.DescargarArchivoAsync(Usuario, PWD, NombreArchivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DescargarArchivoAsync(ByVal Usuario As String, ByVal PWD As String, ByVal NombreArchivo As String, ByVal userState As Object)
            If (Me.DescargarArchivoOperationCompleted Is Nothing) Then
                Me.DescargarArchivoOperationCompleted = AddressOf Me.OnDescargarArchivoOperationCompleted
            End If
            Me.InvokeAsync("DescargarArchivo", New Object() {Usuario, PWD, NombreArchivo}, Me.DescargarArchivoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDescargarArchivoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DescargarArchivoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DescargarArchivoCompleted(Me, New DescargarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstatusComprobante", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EstatusComprobante(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Receptor As String, ByVal Uuid As String, ByVal Total As Double) As RespuestaEstatusComprobante
            Dim results() As Object = Me.Invoke("EstatusComprobante", New Object() {Usuario, PWD, Emisor, Receptor, Uuid, Total})
            Return CType(results(0),RespuestaEstatusComprobante)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EstatusComprobanteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Receptor As String, ByVal Uuid As String, ByVal Total As Double)
            Me.EstatusComprobanteAsync(Usuario, PWD, Emisor, Receptor, Uuid, Total, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EstatusComprobanteAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Receptor As String, ByVal Uuid As String, ByVal Total As Double, ByVal userState As Object)
            If (Me.EstatusComprobanteOperationCompleted Is Nothing) Then
                Me.EstatusComprobanteOperationCompleted = AddressOf Me.OnEstatusComprobanteOperationCompleted
            End If
            Me.InvokeAsync("EstatusComprobante", New Object() {Usuario, PWD, Emisor, Receptor, Uuid, Total}, Me.EstatusComprobanteOperationCompleted, userState)
        End Sub
        
        Private Sub OnEstatusComprobanteOperationCompleted(ByVal arg As Object)
            If (Not (Me.EstatusComprobanteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EstatusComprobanteCompleted(Me, New EstatusComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbresConsumidosRFecha", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbresConsumidosRFecha(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Inicio As Date, ByVal Fin As Date) As RespuestaConsumo
            Dim results() As Object = Me.Invoke("TimbresConsumidosRFecha", New Object() {Usuario, PWD, Emisor, Inicio, Fin})
            Return CType(results(0),RespuestaConsumo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbresConsumidosRFechaAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Inicio As Date, ByVal Fin As Date)
            Me.TimbresConsumidosRFechaAsync(Usuario, PWD, Emisor, Inicio, Fin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbresConsumidosRFechaAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal Inicio As Date, ByVal Fin As Date, ByVal userState As Object)
            If (Me.TimbresConsumidosRFechaOperationCompleted Is Nothing) Then
                Me.TimbresConsumidosRFechaOperationCompleted = AddressOf Me.OnTimbresConsumidosRFechaOperationCompleted
            End If
            Me.InvokeAsync("TimbresConsumidosRFecha", New Object() {Usuario, PWD, Emisor, Inicio, Fin}, Me.TimbresConsumidosRFechaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbresConsumidosRFechaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbresConsumidosRFechaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbresConsumidosRFechaCompleted(Me, New TimbresConsumidosRFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimbresConsumidosMesActual", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TimbresConsumidosMesActual(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String) As RespuestaConsumo
            Dim results() As Object = Me.Invoke("TimbresConsumidosMesActual", New Object() {Usuario, PWD, Emisor})
            Return CType(results(0),RespuestaConsumo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TimbresConsumidosMesActualAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String)
            Me.TimbresConsumidosMesActualAsync(Usuario, PWD, Emisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TimbresConsumidosMesActualAsync(ByVal Usuario As String, ByVal PWD As String, ByVal Emisor As String, ByVal userState As Object)
            If (Me.TimbresConsumidosMesActualOperationCompleted Is Nothing) Then
                Me.TimbresConsumidosMesActualOperationCompleted = AddressOf Me.OnTimbresConsumidosMesActualOperationCompleted
            End If
            Me.InvokeAsync("TimbresConsumidosMesActual", New Object() {Usuario, PWD, Emisor}, Me.TimbresConsumidosMesActualOperationCompleted, userState)
        End Sub
        
        Private Sub OnTimbresConsumidosMesActualOperationCompleted(ByVal arg As Object)
            If (Not (Me.TimbresConsumidosMesActualCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TimbresConsumidosMesActualCompleted(Me, New TimbresConsumidosMesActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaActivarCliente
        
        Private codigoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaConsumo
        
        Private codigoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaEstatusComprobante
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private esCancelableField As String
        
        Private estadoField As String
        
        Private estatusCancelacionField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EsCancelable() As String
            Get
                Return Me.esCancelableField
            End Get
            Set
                Me.esCancelableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstatusCancelacion() As String
            Get
                Return Me.estatusCancelacionField
            End Get
            Set
                Me.estatusCancelacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaDescargarArchivo
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private archivoField() As Byte
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Archivo() As Byte()
            Get
                Return Me.archivoField
            End Get
            Set
                Me.archivoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaCancelacion
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private xMLField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML() As String
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaTimbrado
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private xMLField As String
        
        Private pDFField() As Byte
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML() As String
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaAgregarCliente
        
        Private codigoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ActivarDesactivarClienteCompletedEventHandler(ByVal sender As Object, ByVal e As ActivarDesactivarClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ActivarDesactivarClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaActivarCliente
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaActivarCliente)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ValidarRFCCompletedEventHandler(ByVal sender As Object, ByVal e As ValidarRFCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidarRFCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaActivarCliente
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaActivarCliente)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub RegistrarClienteCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaAgregarCliente
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaAgregarCliente)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbrarCompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbrado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbrado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbrarPruebaCompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarPruebaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarPruebaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbrado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbrado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbrarSAPPruebasCompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarSAPPruebasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarSAPPruebasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbrado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbrado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbrarSAPCompletedEventHandler(ByVal sender As Object, ByVal e As TimbrarSAPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbrarSAPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbrado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbrado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub CancelarComprobanteCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarComprobanteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarComprobanteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub CancelarComprobantePruebasCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarComprobantePruebasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarComprobantePruebasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GenerarPemCompletedEventHandler(ByVal sender As Object, ByVal e As GenerarPemCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerarPemCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub SubirArchivoCompletedEventHandler(ByVal sender As Object, ByVal e As SubirArchivoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SubirArchivoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub DescargarArchivoCompletedEventHandler(ByVal sender As Object, ByVal e As DescargarArchivoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DescargarArchivoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaDescargarArchivo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaDescargarArchivo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub EstatusComprobanteCompletedEventHandler(ByVal sender As Object, ByVal e As EstatusComprobanteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EstatusComprobanteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEstatusComprobante
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEstatusComprobante)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbresConsumidosRFechaCompletedEventHandler(ByVal sender As Object, ByVal e As TimbresConsumidosRFechaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbresConsumidosRFechaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsumo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsumo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TimbresConsumidosMesActualCompletedEventHandler(ByVal sender As Object, ByVal e As TimbresConsumidosMesActualCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TimbresConsumidosMesActualCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsumo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsumo)
            End Get
        End Property
    End Class
End Namespace
